### ISSUE TITLE
Missing return in product->getTargetField

### ISSUE THREAD

**Issue by Mark-H** [tonyklapatch/Commerce_DbTableProductType#1]
https://github.com/tonyklapatch/Commerce_DbTableProductType/blob/master/model/commerce_db-table-product-type/dbtableproducttypeproduct.class.php#L241 should have the `return`. Doesn't look like you're using the getTargetField method, but might as well make it work ;)

**Comment by tonyklapatch** [comment]
No wonder it wasn't getting the value, fixed. Thanks Mark.
